name: YAWL build

on:
  push:
    branches:
      - feature/**
      - fix/**
      - hotfix/**
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7
      - name: Install dependencies
        run: |
          poetry install
      - name: Execute checks
        run: |
          poetry run black --check yawl tests
          poetry run mypy yawl tests
          poetry run flake8 .
          poetry run pytest -n 4
          poetry run poetry check
          poetry run safety check --full-report
