name: YAWL build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7
      - name: Install dependencies
        run: |
          poetry install
      - name: Publish
        with:
          pypi_password: ${{ secrets.PYPI_API_KEY }}
          pypi_username: ${{ secrets.PYPI_USERNAME }}
        run: |
          poetry publish \
          --build \
          --password $pypi_password \
          --username $pypi_username
