name: YAWL checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          echo "export PATH=$PATH:$HOME/.local/bin" > ~/.bash_profile && source ~/.bash_profile
          source "$HOME/.poetry/env"
          poetry config virtualenvs.in-project true
          poetry install
      - name: Execute checks
        run: |
          make checks
