name: YAWL build

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.7
      - name: Install dependencies
        run: |
          poetry install
      - name: Execute checks
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_API_KEY }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: |
          poetry publish \
          --build \
          --password $PYPI_PASSWORD \
          --username $PYPI_USERNAME
